version: '3'
services:
  backend:
    build:
      context: ./podlingo-backend
    environment:
      - MONGO_URI=${MONGO_URI}  # Using variable from .env
      - NODE_ENV=production
    ports:
      - '5000:5000'
  frontend:
    build:
      context: ./podlingo-frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000/api}
    ports:
      - '3000:80'