services:
  backend:
    build:
      context: ./podlingo-backend
      dockerfile: Dockerfile  # Use the production Dockerfile
      args:
        PODCAST_INDEX_API_KEY: ${PODCAST_INDEX_API_KEY}
        PODCAST_INDEX_API_SECRET: ${PODCAST_INDEX_API_SECRET}
        CLIENT_URL: ${CLIENT_URL}
    environment:
      - MONGO_URI=${MONGO_URI}  # Environment variables for production
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '5000:5000'
    networks:
      - app-network

  frontend:
    build:
      context: ./podlingo-frontend
      dockerfile: Dockerfile  # Use the production Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000/api}
    ports:
      - '3000:80'  # Map to port 80 for production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
