services:
  backend:
    build:
      context: ./podlingo-backend
      dockerfile: Dockerfile.dev
      args:
        PODCAST_INDEX_API_KEY: ${PODCAST_INDEX_API_KEY}
        PODCAST_INDEX_API_SECRET: ${PODCAST_INDEX_API_SECRET}
        CLIENT_URL: ${CLIENT_URL}
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true  # Windows -.-
    ports:
      - '5000:5000'
    volumes:
      - ./podlingo-backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./podlingo-frontend
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000/api}
    ports:
      - '3000:3000'
    volumes:
      - ./podlingo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true  # Windows -.-
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend
