# Frontend Development Dockerfile
FROM node:20.9.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

# Use build argument for environment variable
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

# Expose the default React app port
EXPOSE 3000

CMD [ "npm", "run", "dev"] # Starts the React app with hot reloading
